import type { Review, VehicleWithImages } from "@/types/database";

export const DEMO_IMAGES: Record<string, string> = {
  "toyota-rav4-limited-2021":
    "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=85",
  "toyota-hilux-srx-2022":
    "https://images.unsplash.com/photo-1494905998402-395d579af36f?w=1200&q=85",
  "ford-ranger-xlt-2021":
    "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=85",
  "hyundai-tucson-2022":
    "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=85",
  "mazda-cx5-2020":
    "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=1200&q=85",
  "chevrolet-trailblazer-2021":
    "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200&q=85",
  "porsche-cayenne-2021": "/featured-1.jpg",
  "mercedes-e300-2020": "/featured-2.jpg",
  "bmw-x5-2022": "/featured-3.jpg",
};

function v(
  partial: Omit<
    VehicleWithImages,
    "created_at" | "updated_at" | "vehicle_images" | "published" | "plate" | "stock_id" | "location" | "origin" | "status"
  > & {
    published?: boolean;
    featured: boolean;
    plate?: string | null;
    stock_id?: string | null;
    location?: string | null;
    origin?: string | null;
    status?: VehicleWithImages["status"];
  }
): VehicleWithImages {
  const published = partial.published ?? true;
  return {
    ...partial,
    plate: partial.plate ?? null,
    stock_id: partial.stock_id ?? null,
    location: partial.location ?? null,
    origin: partial.origin ?? null,
    status: partial.status ?? (published ? "Disponible" : "Borrador"),
    published,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    vehicle_images: [
      {
        id: `img-${partial.id}`,
        vehicle_id: partial.id,
        storage_path: `demo/${partial.slug}.jpg`,
        sort_order: 0,
        created_at: "",
      },
    ],
  };
}

export const MOCK_VEHICLES: VehicleWithImages[] = [
  v({
    id: "1",
    slug: "porsche-cayenne-2021",
    brand: "Porsche",
    model: "Cayenne",
    year: 2021,
    version: "3.0 V6",
    category: "SUV",
    fuel: "Gasolina",
    transmission: "Automática",
    mileage: 28000,
    color: "Negro",
    doors: 4,
    engine: "3.0L",
    price: 62990000,
    description: "Porsche Cayenne en impecable estado.",
    featured: true,
  }),
  v({
    id: "2",
    slug: "mercedes-e300-2020",
    brand: "Mercedes-Benz",
    model: "E 300",
    year: 2020,
    version: "E 300",
    category: "Sedán",
    fuel: "Gasolina",
    transmission: "Automática",
    mileage: 35000,
    color: "Plata",
    doors: 4,
    engine: "2.0L",
    price: 39990000,
    description: "Mercedes-Benz E 300 full equipo.",
    featured: true,
  }),
  v({
    id: "3",
    slug: "bmw-x5-2022",
    brand: "BMW",
    model: "X5",
    year: 2022,
    version: "xDrive40i",
    category: "SUV",
    fuel: "Gasolina",
    transmission: "Automática",
    mileage: 22000,
    color: "Negro",
    doors: 4,
    engine: "3.0L",
    price: 54990000,
    description: "BMW X5 xDrive40i.",
    featured: true,
  }),
  v({
    id: "4",
    slug: "toyota-hilux-srx-2022",
    brand: "Toyota",
    model: "Hilux",
    year: 2022,
    version: "2.8 D4D SRX 4X4 AT",
    category: "Camioneta",
    fuel: "Diésel",
    transmission: "Automática",
    mileage: 32000,
    color: "Negro",
    doors: 4,
    engine: "2.8L",
    price: 28990000,
    description: "Hilux SRX impecable.",
    featured: false,
  }),
  v({
    id: "5",
    slug: "mazda-cx5-2020",
    brand: "Mazda",
    model: "CX-5",
    year: 2020,
    version: "2.0 Skyactiv GT",
    category: "SUV",
    fuel: "Gasolina",
    transmission: "Automática",
    mileage: 48000,
    color: "Rojo",
    doors: 4,
    engine: "2.0L",
    price: 17990000,
    description: "CX-5 GT diseño premium.",
    featured: false,
  }),
  v({
    id: "6",
    slug: "toyota-rav4-limited-2021",
    brand: "Toyota",
    model: "RAV4",
    year: 2021,
    version: "2.5 Limited 4x4",
    category: "SUV",
    fuel: "Gasolina",
    transmission: "Automática",
    mileage: 45800,
    color: "Gris Oscuro",
    doors: 4,
    engine: "2.5L",
    price: 22990000,
    description: "RAV4 Limited 4x4.",
    featured: false,
  }),
  v({
    id: "7",
    slug: "ford-ranger-xlt-2021",
    brand: "Ford",
    model: "Ranger",
    year: 2021,
    version: "XLT 3.2 4x4",
    category: "Camioneta",
    fuel: "Diésel",
    transmission: "Automática",
    mileage: 51000,
    color: "Plata",
    doors: 4,
    engine: "3.2L",
    price: 24990000,
    description: "Ranger XLT.",
    featured: false,
  }),
  v({
    id: "8",
    slug: "hyundai-tucson-2022",
    brand: "Hyundai",
    model: "Tucson",
    year: 2022,
    version: "2.0 Premium",
    category: "SUV",
    fuel: "Gasolina",
    transmission: "Automática",
    mileage: 28000,
    color: "Azul",
    doors: 4,
    engine: "2.0L",
    price: 19990000,
    description: "Tucson Premium.",
    featured: false,
  }),
  v({
    id: "9",
    slug: "chevrolet-trailblazer-2021",
    brand: "Chevrolet",
    model: "Trailblazer",
    year: 2021,
    version: "1.3 Premier",
    category: "SUV",
    fuel: "Gasolina",
    transmission: "Automática",
    mileage: 41000,
    color: "Blanco",
    doors: 4,
    engine: "1.3L Turbo",
    price: 15990000,
    description: "Trailblazer Premier.",
    featured: false,
  }),
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "r1",
    nombre: "Carlos M.",
    ciudad: "Puerto Montt",
    rating: 5,
    texto: "Excelente atención. Me ayudaron con el financiamiento y entregué el mismo día.",
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "r2",
    nombre: "María P.",
    ciudad: "Osorno",
    rating: 5,
    texto: "El auto estaba impecable. Todo transparente, sin sorpresas.",
    published: true,
    created_at: new Date().toISOString(),
  },
  {
    id: "r3",
    nombre: "Jorge R.",
    ciudad: "Puerto Varas",
    rating: 5,
    texto: "Compré mi Hilux acá. Proceso rápido y profesional.",
    published: true,
    created_at: new Date().toISOString(),
  },
];
